README.md
insuree/models.py

Insuree init

---

insuree/models.py
insuree/schema.py
setup.py

Security moved to get_queryset.
Some reformatting to help spot errors (that's how we spotted one in Claim).
Not really sure about the criteria to filter the insuree visible to someone, specifically to link insurees to locations

Fhir fine grained security

---

insuree/apps.py
insuree/gql_queries.py
insuree/models.py
insuree/schema.py
insuree/signals.py

TICKET: https://openimis.atlassian.net/browse/OFS-281
with additional filter processing via django signal.
example of patload

OFS-281: Create GraphQL queries for the Insuree policy

---

insuree/gql_mutations.py

Part of [OTC-289](https://openimis.atlassian.net/browse/OTC-289)

OTC-289: Contribution point included in Family GQL Type

---

insuree/schema.py
insuree/signals.py

TICKET: [OTC-303](https://openimis.atlassian.net/browse/OTC-303)

OTC-303: Additional filter handling

---

.github/workflows/openmis-module-test.yml
insuree/gql_mutations.py
insuree/services.py

[https://openimis.atlassian.net/browse/OPL-71](https://openimis.atlassian.net/browse/OPL-71)
Changes:
- Moved business logic from gql mutations to services
- Adjusted mutations code to use new services

OPL-71 Move Insuree business logic from GQL mutations to services

---

insuree/gql_mutations.py
insuree/schema.py
insuree/services.py
insuree/tests/test_graphql.py

Part of [OP-818](https://openimis.atlassian.net/browse/OP-818)

OP-818: Fixed Insuree Number validation

---

insuree/migrations/0007_auto_20200722_0940.py
insuree/migrations/0008_auto_20200731_0443.py
insuree/migrations/0010_auto_20200731_0524.py
insuree/migrations/0011_auto_20200807_1309.py
insuree/migrations/0013_auto_20211103_1023.py
insuree/models.py
insuree/schema.py

Django 3.1

---

insuree/gql_mutations.py

Was fixed in front too but necessary in backend too

OMT-301 Gender should be mandatory

---

insuree/schema.py
insuree/tests/test_insuree_photo.py

https://openimis.atlassian.net/browse/OP-1027

OP-1027: modular IMIS: the front end doesn't support portability of benefits.

---

insuree/gql_mutations.py
insuree/schema.py
insuree/services.py
insuree/tests/test_graphql.py
insuree/tests/test_insuree_photo.py

https://openimis.atlassian.net/browse/OP-1080
It is related to its frontend part: https://github.com/openimis/openimis-fe-insuree_js/pull/37

OP-1080: update backend logic for Insuree number validation

---

.github/workflows/openmis-module-test.yml
insuree/apps.py
insuree/schema.py
insuree/services.py
insuree/tests/test_graphql.py

Ticket: https://openimis.atlassian.net/browse/OTC-811
Required dependency:
https://github.com/openimis/openimis-be-core_py/pull/148
Changes:
- Validation query now returns code and error message in addition to a true/false value.
- Query now checks whether user has required permissions.

OTC-811: Error messages added for insuree code validation.

---

.github/workflows/openmis-module-test.yml
insuree/schema.py

https://openimis.atlassian.net/browse/OTC-894

OTC-894: Families list is not limited to the user's mapped location

---

insuree/schema.py
insuree/signals.py

This change was introduced during development of the training materials. 
In future it'll allow easier extension of insuree filtering options.

Signal for filter extension in insuree query

---

insuree/apps.py

https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.

OP-1518: load config

---

insuree/services.py

https://openimis.atlassian.net/browse/OP-1668
FileNotFoundError handled while opening a photo of an insuree

OP-1668: Handle the exception when picture is not available for an insuree

---

insuree/tests/test_reports.py

https://openimis.atlassian.net/browse/OP-1675
Single claim report test added

OP-1675: Insuree: Tests for reports missing

---

insuree/services.py

Ticket: https://openimis.atlassian.net/browse/OP-1686
Changes:
- Removed redundant validation of insuree status
- If no status is provided it will be assumed to be active

OP-1686: Removed redundant validation.

---

insuree/gql_queries.py

Ticket: https://openimis.atlassian.net/browse/OP-1721
FE: https://github.com/openimis/openimis-fe-insuree_js/pull/112
Changes:
- New field added in insuree search - family

OP-1721: Added family field to insuree gql search.

---

insuree/apps.py
insuree/services.py

Ticket: https://openimis.atlassian.net/browse/ONI-156
FE PR: https://github.com/openimis/openimis-fe-insuree_js/pull/116
Changes:
- Added setting for photo to be required
- If required - saving is throwing an error without photo.

ONI-156: Insuree photo required on setting.

---

insuree/services.py

https://openimis.atlassian.net/browse/OP-1780

OP-1780: Unit tests for Insuree module fails

---

insuree/schema.py

[https://openimis.atlassian.net/browse/OM-118](https://openimis.atlassian.net/browse/OM-118)

OM-118 Added export feature for insurees query

---

insuree/tests/test_graphql.py

MERGING develop into release/24.04

MERGING develop into release/24.04

---

insuree/reports/enrolled_families.py

https://openimis.atlassian.net/browse/OP-1976
Enrolled Families report converted to ORM and dropped the stored procedure

OP-1976: Generate insuree family overview report  crashes

---

insuree/schema.py

Ticket:
https://openimis.atlassian.net/browse/CQI-161
Changes:
- input limitations added for insuree no

CQI-161: added insuree parameter limit for backend query

---

insuree/apps.py
insuree/gql_mutations.py
insuree/gql_queries.py
insuree/models.py
insuree/reports/insuree_family_overview.py
insuree/schema.py
insuree/services.py
insuree/test_helpers.py
insuree/tests/test_graphql.py
insuree/tests/test_insuree_photo.py

MERGING release/24.04 into main

MERGING release/24.04 into main
